-- Generated by scripts/generate-seed.js from src/data/mountains.json. Do not edit by hand.
-- Mountain identities currently used by the supported collections. Null GPS fields
-- are intentional: pending verification points must never be guessed or activated.

insert into public.mountains
  (slug, name_ko, name_en, altitude_m, region, latitude, longitude, verification_radius_m, image_url, mascot_key, description, display_order)
values
  ('hallasan', '한라산', 'Hallasan', 1947, '제주', 33.362, 126.529, 100, null, 'hallasan', '남한에서 가장 높은 산. 백록담까지 오르는 성판악·관음사 코스는 계절마다 완전히 다른 얼굴을 보여줘요.', 1),
  ('jirisan', '지리산', 'Jirisan', 1915, '경상', 35.337, 127.731, 100, null, 'jirisan', '세 개의 도에 걸친 거대한 산맥. 천왕봉 일출은 3대가 덕을 쌓아야 본다는 말이 있어요.', 2),
  ('seoraksan', '설악산', 'Seoraksan', 1708, '강원', 38.119, 128.466, 100, null, 'seoraksan', '대청봉과 울산바위, 공룡능선까지. 한국에서 가장 극적인 바위 풍경을 가진 산이에요.', 3),
  ('bukhansan', '북한산', 'Bukhansan', 836, '서울·경기', 37.659, 126.978, 100, null, 'bukhansan', '서울 한복판에서 화강암 봉우리를 오를 수 있는 산. 백운대 정상은 도심 뷰가 압권이에요.', 4),
  ('deogyusan', '덕유산', 'Deogyusan', 1614, '전라', 35.86, 127.746, 100, null, 'deogyusan', '겨울 상고대로 유명한 향적봉. 곤돌라로 오르면 설경을 비교적 편하게 만날 수 있어요.', 5),
  ('sobaeksan', '소백산', 'Sobaeksan', 1440, '충청', 36.957, 128.484, 100, null, 'sobaeksan', '부드러운 능선과 5월 철쭉 군락, 비로봉의 세찬 바람이 기억에 남는 산이에요.', 6),
  ('gyebangsan', '계방산', 'Gyebangsan', 1577, '강원', 37.729, 128.476, 100, null, 'gyebangsan', null, 7),
  ('taebaeksan', '태백산', 'Taebaeksan', 1567, '강원', 37.096, 128.916, 100, null, 'taebaeksan', null, 8),
  ('odaesan', '오대산', 'Odaesan', 1563, '강원', 37.797, 128.543, 100, null, 'odaesan', null, 9),
  ('gariwangsan', '가리왕산', 'Gariwangsan', 1561, '강원', 37.462, 128.562, 100, null, 'gariwangsan', null, 10),
  ('hwaaksan', '화악산', 'Hwaaksan', 1468, '서울·경기', 37.993, 127.502, 100, null, 'hwaaksan', null, 11),
  ('bangtaesan', '방태산', 'Bangtaesan', 1444, '강원', 37.895, 128.365, 100, null, 'bangtaesan', null, 12),
  ('gayasan', '가야산', 'Gayasan', 1430, '경상', 35.823, 128.123, 100, null, 'gayasan', null, 13),
  ('jeombongsan', '점봉산', 'Jeombongsan', 1424, '강원', 38.048, 128.428, 100, null, 'jeombongsan', null, 14),
  ('dutasan', '두타산', 'Dutasan', 1353, '강원', 37.443, 129.018, 100, null, 'dutasan', null, 15),
  ('baekdeoksan', '백덕산', 'Baekdeoksan', 1350, '강원', 37.402, 128.313, 100, null, 'baekdeoksan', null, 16),
  ('daeamsan', '대암산', 'Daeamsan', 1304, '강원', 38.213, 128.127, 100, null, 'daeamsan', null, 17),
  ('chiaksan', '치악산', 'Chiaksan', 1288, '강원', 37.372, 128.055, 100, null, 'chiaksan', null, 18),
  ('myeongjisan', '명지산', 'Myeongjisan', 1267, '서울·경기', 37.937, 127.435, 100, null, 'myeongjisan', null, 19),
  ('minjujisan', '민주지산', 'Minjujisan', 1242, '충청', 36.032, 127.873, 100, null, 'minjujisan', null, 20),
  ('gajisan', '가지산', 'Gajisan', 1241, '경상', 35.622, 129.003, 100, null, 'gajisan', null, 21),
  ('jangansan', '장안산', 'Jangansan', 1237, '전라', 35.64, 127.585, 100, null, 'jangansan', null, 22),
  ('baegunsan-gwangyang', '백운산 (광양)', 'Baegunsan (Gwangyang)', 1222, '전라', 35.104, 127.622, 100, null, 'baegunsan-gwangyang', null, 23),
  ('unmunsan', '운문산', 'Unmunsan', 1195, '경상', 35.602, 128.96, 100, null, 'unmunsan', null, 24),
  ('palgongsan', '팔공산', 'Palgongsan', 1193, '경상', 36.017, 128.695, 100, null, 'palgongsan', null, 25),
  ('hwangseoksan', '황석산', 'Hwangseoksan', 1190, '경상', 35.7, 127.78, 100, null, 'hwangseoksan', null, 26),
  ('mudeungsan', '무등산', 'Mudeungsan', 1187, '전라', 35.134, 126.989, 100, null, 'mudeungsan', null, 27),
  ('sinbulsan', '신불산', 'Sinbulsan', 1159, '경상', 35.545, 129.052, 100, null, 'sinbulsan', null, 28),
  ('yongmunsan', '용문산', 'Yongmunsan', 1157, '서울·경기', 37.565, 127.55, 100, null, 'yongmunsan', null, 29),
  ('unjangsan', '운장산', 'Unjangsan', 1126, '전라', 35.912, 127.365, 100, null, 'unjangsan', null, 30),
  ('hwangaksan', '황악산', 'Hwangaksan', 1111, '경상', 36.116, 127.996, 100, null, 'hwangaksan', null, 31),
  ('jaeyaksan', '재약산', 'Jaeyaksan', 1108, '경상', 35.529, 128.986, 100, null, 'jaeyaksan', null, 32),
  ('hwangmaesan', '황매산', 'Hwangmaesan', 1108, '경상', 35.487, 127.975, 100, null, 'hwangmaesan', null, 33),
  ('juheulsan', '주흘산', 'Juheulsan', 1106, '경상', 36.798, 128.087, 100, null, 'juheulsan', null, 34),
  ('woraksan', '월악산', 'Woraksan', 1097, '충청', 36.887, 128.093, 100, null, 'woraksan', null, 35),
  ('biseulsan', '비슬산', 'Biseulsan', 1084, '경상', 35.718, 128.522, 100, null, 'biseulsan', null, 36),
  ('hwangjangsan', '황장산', 'Hwangjangsan', 1077, '경상', 36.788, 128.238, 100, null, 'hwangjangsan', null, 37),
  ('deokhangsan', '덕항산', 'Deokhangsan', 1071, '강원', 37.338, 128.982, 100, null, 'deokhangsan', null, 38),
  ('songnisan', '속리산', 'Songnisan', 1058, '충청', 36.543, 127.87, 100, null, 'songnisan', null, 39),
  ('garisan', '가리산', 'Garisan', 1051, '강원', 37.875, 127.96, 100, null, 'garisan', null, 40),
  ('jeoksangsan', '적상산', 'Jeoksangsan', 1034, '전라', 35.958, 127.694, 100, null, 'jeoksangsan', null, 41),
  ('taehwasan', '태화산', 'Taehwasan', 1027, '강원', 37.108, 128.484, 100, null, 'taehwasan', null, 42),
  ('geumsusan', '금수산', 'Geumsusan', 1016, '충청', 36.998, 128.266, 100, null, 'geumsusan', null, 43),
  ('eungbongsan', '응봉산', 'Eungbongsan', 999, '경상', 37.075, 129.29, 100, null, 'eungbongsan', null, 44),
  ('huiyangsan', '희양산', 'Huiyangsan', 998, '경상', 36.74, 128.017, 100, null, 'huiyangsan', null, 45),
  ('seonginbong', '성인봉', 'Seonginbong', 984, '경상', 37.505, 130.865, 100, null, 'seonginbong', null, 46),
  ('geumosan', '금오산', 'Geumosan', 976, '경상', 36.098, 128.301, 100, null, 'geumosan', null, 47),
  ('doraksan', '도락산', 'Doraksan', 964, '충청', 36.883, 128.336, 100, null, 'doraksan', null, 48),
  ('unaksan', '운악산', 'Unaksan', 936, '서울·경기', 37.883, 127.32, 100, null, 'unaksan', null, 49),
  ('daeyasan', '대야산', 'Daeyasan', 931, '충청', 36.683, 127.94, 100, null, 'daeyasan', null, 50),
  ('myeongseongsan', '명성산', 'Myeongseongsan', 923, '서울·경기', 38.108, 127.33, 100, null, 'myeongseongsan', null, 51),
  ('cheonseongsan', '천성산', 'Cheonseongsan', 922, '경상', 35.437, 129.093, 100, null, 'cheonseongsan', null, 52),
  ('baegunsan-pocheon', '백운산 (포천)', 'Baegunsan (Pocheon)', 904, '서울·경기', 38.077, 127.435, 100, null, 'baegunsan-pocheon', null, 53),
  ('seodaesan', '서대산', 'Seodaesan', 904, '충청', 36.23, 127.55, 100, null, 'seodaesan', null, 54),
  ('gongjaksan', '공작산', 'Gongjaksan', 887, '강원', 37.725, 128.02, 100, null, 'gongjaksan', null, 55),
  ('chungnyeongsan', '축령산', 'Chungnyeongsan', 887, '서울·경기', 37.813, 127.335, 100, null, 'chungnyeongsan', null, 56),
  ('jogyesan', '조계산', 'Jogyesan', 884, '전라', 35.001, 127.312, 100, null, 'jogyesan', null, 57),
  ('baegunsan-jeongseon', '백운산 (정선)', 'Baegunsan (Jeongseon)', 883, '강원', 37.32, 128.72, 100, null, 'baegunsan-jeongseon', null, 58),
  ('daedunsan', '대둔산', 'Daedunsan', 878, '충청', 36.121, 127.324, 100, null, 'daedunsan', null, 59),
  ('yonghwasan', '용화산', 'Yonghwasan', 878, '강원', 38.007, 127.716, 100, null, 'yonghwasan', null, 60),
  ('gubyeongsan', '구병산', 'Gubyeongsan', 876, '충청', 36.437, 127.845, 100, null, 'gubyeongsan', null, 61),
  ('cheongnyangsan', '청량산', 'Cheongnyangsan', 870, '경상', 36.797, 128.907, 100, null, 'cheongnyangsan', null, 62),
  ('yumyeongsan', '유명산', 'Yumyeongsan', 862, '서울·경기', 37.598, 127.483, 100, null, 'yumyeongsan', null, 63),
  ('gyeryongsan', '계룡산', 'Gyeryongsan', 845, '충청', 36.342, 127.206, 100, null, 'gyeryongsan', null, 64),
  ('cheonmasan', '천마산', 'Cheonmasan', 812, '서울·경기', 37.678, 127.276, 100, null, 'cheonmasan', null, 65),
  ('wolchulsan', '월출산', 'Wolchulsan', 809, '전라', 34.766, 126.706, 100, null, 'wolchulsan', null, 66),
  ('geumjeongsan', '금정산', 'Geumjeongsan', 802, '경상', 35.283, 129.053, 100, null, 'geumjeongsan', null, 67),
  ('moaksan', '모악산', 'Moaksan', 794, '전라', 35.732, 127.078, 100, null, 'moaksan', null, 68),
  ('oseosan', '오서산 (보령)', 'Oseosan (Boryeong)', 791, '충청', null, null, null, null, null, '충남 보령과 홍성에 걸친 억새 명산이에요. BAC 기준 오서산 도전 대상이며 인증지 좌표는 검증 중이에요.', 69),
  ('obongsan', '오봉산', 'Obongsan', 779, '강원', 37.983, 127.742, 100, null, 'obongsan', null, 70),
  ('naejangsan', '내장산', 'Naejangsan', 763, '전라', 35.478, 126.887, 100, null, 'naejangsan', null, 71),
  ('muhaksan', '무학산', 'Muhaksan', 761, '경상', 35.204, 128.539, 100, null, 'muhaksan', null, 72),
  ('hwawangsan', '화왕산', 'Hwawangsan', 757, '경상', 35.542, 128.545, 100, null, 'hwawangsan', null, 73),
  ('bangjangsan', '방장산', 'Bangjangsan', 743, '전라', 35.435, 126.784, 100, null, 'bangjangsan', null, 74),
  ('baegamsan', '백암산', 'Baegamsan', 741, '전라', 35.466, 126.848, 100, null, 'baegamsan', null, 75),
  ('dobongsan', '도봉산', 'Dobongsan', 740, '서울·경기', 37.7, 127.014, 100, null, 'dobongsan', null, 76),
  ('chuwolsan', '추월산', 'Chuwolsan', 731, '전라', 35.406, 126.996, 100, null, 'chuwolsan', null, 77),
  ('cheongwansan', '천관산', 'Cheongwansan', 723, '전라', 34.531, 126.919, 100, null, 'cheongwansan', null, 78),
  ('juwangsan', '주왕산', 'Juwangsan', 721, '경상', 36.388, 129.145, 100, null, 'juwangsan', null, 79),
  ('cheontaesan', '천태산', 'Cheontaesan', 715, '충청', 36.117, 127.639, 100, null, 'cheontaesan', null, 80),
  ('naeyeonsan', '내연산', 'Naeyeonsan', 710, '경상', 36.264, 129.283, 100, null, 'naeyeonsan', null, 81),
  ('duryunsan', '두륜산', 'Duryunsan', 703, '전라', 34.482, 126.616, 100, null, 'duryunsan', null, 82),
  ('maisan', '마이산', 'Maisan', 686, '전라', 35.762, 127.406, 100, null, 'maisan', null, 83),
  ('geumsan', '금산', 'Geumsan', 681, '경상', 34.755, 127.98, 100, null, 'geumsan', null, 84),
  ('gamaksan', '감악산', 'Gamaksan', 675, '서울·경기', 37.943, 126.968, 100, null, 'gamaksan', null, 85),
  ('samaksan', '삼악산', 'Samaksan', 654, '강원', 37.834, 127.667, 100, null, 'samaksan', null, 86),
  ('gwanaksan', '관악산', 'Gwanaksan', 632, '서울·경기', 37.443, 126.964, 100, null, 'gwanaksan', null, 87),
  ('paryeongsan', '팔영산', 'Paryeongsan', 608, '전라', 34.615, 127.435, 100, null, 'paryeongsan', null, 88),
  ('soyosan', '소요산', 'Soyosan', 587, '서울·경기', 37.947, 127.09, 100, null, 'soyosan', null, 89),
  ('gangcheonsan', '강천산', 'Gangcheonsan', 584, '전라', 35.404, 127.055, 100, null, 'gangcheonsan', null, 90),
  ('chilgapsan', '칠갑산', 'Chilgapsan', 561, '충청', 36.393, 126.885, 100, null, 'chilgapsan', null, 91),
  ('yeonhwasan', '연화산', 'Yeonhwasan', 528, '경상', 35.045, 128.245, 100, null, 'yeonhwasan', null, 92),
  ('byeonsan', '변산', 'Byeonsan', 508, '전라', 35.649, 126.578, 100, null, 'byeonsan', null, 93),
  ('deoksungsan', '덕숭산', 'Deoksungsan', 495, '충청', 36.664, 126.617, 100, null, 'deoksungsan', null, 94),
  ('manisan', '마니산', 'Manisan', 469, '서울·경기', 37.61, 126.433, 100, null, 'manisan', null, 95),
  ('namsan-gyeongju', '남산', 'Namsan (Gyeongju)', 468, '경상', 35.78, 129.226, 100, null, 'namsan-gyeongju', null, 96),
  ('mireuksan', '미륵산', 'Mireuksan', 461, '경상', 34.816, 128.417, 100, null, 'mireuksan', null, 97),
  ('jirisan-tongyeong', '지리산 (통영)', 'Jirisan (Tongyeong)', 398, '경상', 34.86, 128.199, 100, null, 'jirisan-tongyeong', null, 98),
  ('seonunsan', '선운산', 'Seonunsan', 336, '전라', 35.503, 126.575, 100, null, 'seonunsan', null, 99),
  ('palbongsan', '팔봉산', 'Palbongsan', 327, '강원', 37.72, 127.767, 100, null, 'palbongsan', null, 100),
  ('suraksan', '수락산', 'Suraksan', 640, '서울·경기', null, null, null, null, null, '서울 북동쪽과 남양주 경계에 솟은 바위산이에요. 도심에서 능선과 암릉 풍경을 가깝게 만날 수 있어요.', 101),
  ('cheonggyesan-seoul', '청계산', 'Cheonggyesan (Seoul)', 582, '서울·경기', null, null, null, null, null, '서울 남쪽 여러 도시의 경계를 잇는 친근한 산이에요. BAC 도전에서는 매봉을 인증지로 안내해요.', 102),
  ('yeoninsan', '연인산', 'Yeoninsan', 1068, '서울·경기', null, null, null, null, null, '가평의 깊은 능선과 계곡을 품은 산이에요. 봄 철쭉과 부드럽게 이어지는 능선길로 알려져 있어요.', 103),
  ('gamaksan-wonju', '감악산 (원주)', 'Gamaksan (Wonju)', 945, '강원', null, null, null, null, null, '원주와 제천 경계의 감악산이에요. 경기 파주의 감악산과는 다른 산 정체성으로 관리해요.', 104),
  ('odaesan-noinbong', '오대산 노인봉', 'Odaesan Noinbong', 1338, '강원', null, null, null, null, null, '오대산 권역의 노인봉 도전 대상이에요. 비로봉을 인증하는 오대산 항목과 별도로 기록해요.', 105),
  ('hambaeksan', '함백산', 'Hambaeksan', 1573, '강원', null, null, null, null, null, '태백산맥의 높은 능선을 시원하게 조망할 수 있는 산이에요. 겨울 설경과 야생화 군락으로 사랑받아요.', 106),
  ('cheonghwasan', '청화산', 'Cheonghwasan', 970, '충청', null, null, null, null, null, '괴산의 바위 능선과 백두대간 길이 만나는 산이에요. 주변 명산과 이어 걷는 산행지로도 알려져 있어요.', 107),
  ('chilbosan-goesan', '칠보산 (괴산)', 'Chilbosan (Goesan)', 778, '충청', null, null, null, null, null, '괴산 쌍곡계곡 곁에 자리한 칠보산이에요. 같은 이름의 다른 산과 구분해 별도 정체성으로 관리해요.', 108),
  ('gayasan-yesan', '가야산 (충남)', 'Gayasan (Yesan)', 678, '충청', null, null, null, null, null, '충남 예산의 가야산이에요. 합천·성주의 가야산과 합치지 않고 별도 산으로 기록해요.', 109),
  ('gwangdeoksan-cheonan', '광덕산', 'Gwangdeoksan (Cheonan)', 699, '충청', null, null, null, null, null, '천안 남쪽을 대표하는 산이에요. 완만한 숲길과 정상에서 펼쳐지는 충남 내륙 조망이 매력이에요.', 110),
  ('yongbongsan-hongseong', '용봉산 (홍성)', 'Yongbongsan (Hongseong)', 381, '충청', null, null, null, null, null, '높이는 낮지만 기암이 촘촘히 이어지는 홍성의 바위산이에요. 짧은 산행에서도 다양한 암릉 풍경을 만나요.', 111),
  ('gubongsan-jinan', '구봉산 (진안)', 'Gubongsan (Jinan)', 1002, '전라', null, null, null, null, null, '아홉 봉우리와 구름다리로 알려진 진안의 산이에요. BAC 도전 인증지는 천왕봉이에요.', 112),
  ('jirisan-baraebong', '지리산 바래봉', 'Jirisan Baraebong', 1165, '전라', null, null, null, null, null, '지리산 서북능선의 바래봉 도전 대상이에요. 천왕봉을 인증하는 지리산 항목과 별도로 기록해요.', 113),
  ('jirisan-banyabong', '지리산 반야봉', 'Jirisan Banyabong', 1732, '전라', null, null, null, null, null, '지리산 주능선 가까이 솟은 반야봉 도전 대상이에요. 천왕봉·바래봉과 구분해 독립적으로 기록해요.', 114),
  ('dalmasan', '달마산', 'Dalmasan', 489, '전라', null, null, null, null, null, '해남 땅끝 가까이 병풍처럼 솟은 암릉 산이에요. 낮은 고도와 달리 거친 능선과 남해 조망이 선명해요.', 115),
  ('deongnyongsan', '덕룡산', 'Deongnyongsan', 432, '전라', null, null, null, null, null, '강진의 날카로운 암릉이 용의 등처럼 이어지는 산이에요. BAC 도전에서는 서봉을 인증지로 안내해요.', 116),
  ('dongaksan-gokseong', '동악산 (곡성)', 'Dongaksan (Gokseong)', 735, '전라', null, null, null, null, null, '곡성의 섬진강과 산줄기를 내려다보는 산이에요. BAC 도전 인증지는 시루봉이에요.', 117),
  ('bulgapsan-yeonggwang', '불갑산 (영광)', 'Bulgapsan (Yeonggwang)', 516, '전라', null, null, null, null, null, '영광 불갑사 뒤편에 이어지는 산이에요. 가을 상사화와 부드러운 숲 능선으로 널리 알려져 있어요.', 118),
  ('chungnyeongsan-jangseong', '축령산 (장성)', 'Chungnyeongsan (Jangseong)', 621, '전라', null, null, null, null, null, '장성 편백숲을 품은 축령산이에요. 경기 남양주·가평의 축령산과 합치지 않고 별도 산으로 관리해요.', 119),
  ('joryeongsan', '조령산', 'Joryeongsan', 1026, '경상', null, null, null, null, null, '문경새재 남쪽의 백두대간을 잇는 산이에요. 암릉과 숲길이 번갈아 나타나는 힘 있는 산행지예요.', 120),
  ('gitdaebong-hongdo', '깃대봉 (홍도)', 'Gitdaebong (Hongdo)', 368, '전라', null, null, null, null, null, '홍도의 최고봉으로, 섬과 다도해 풍경을 함께 만나는 산림청 100대 명산이에요. 인증 지점 좌표는 별도 검증 전까지 사용하지 않아요.', 121)
on conflict (slug) do update set
  name_ko = excluded.name_ko,
  name_en = excluded.name_en,
  altitude_m = excluded.altitude_m,
  region = excluded.region,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  verification_radius_m = excluded.verification_radius_m,
  image_url = coalesce(public.mountains.image_url, excluded.image_url),
  mascot_key = excluded.mascot_key,
  description = excluded.description,
  display_order = excluded.display_order;

-- Collection membership is derived from the audited source identities, never name-matched in SQL.
-- The BAC order is the repository's documented staging order, not an official BAC ranking.
create temporary table collection_membership_seed (
  collection_id text not null,
  mountain_slug text not null,
  display_order integer not null,
  source_label text not null,
  verification_point_name text
) on commit drop;

insert into collection_membership_seed (
  collection_id,
  mountain_slug,
  display_order,
  source_label,
  verification_point_name
)
values
  ('forest_service_100', 'hallasan', 1, '산림청 100대 명산', null),
  ('forest_service_100', 'jirisan', 2, '산림청 100대 명산', null),
  ('forest_service_100', 'seoraksan', 3, '산림청 100대 명산', null),
  ('forest_service_100', 'bukhansan', 4, '산림청 100대 명산', null),
  ('forest_service_100', 'deogyusan', 5, '산림청 100대 명산', null),
  ('forest_service_100', 'sobaeksan', 6, '산림청 100대 명산', null),
  ('forest_service_100', 'gyebangsan', 7, '산림청 100대 명산', null),
  ('forest_service_100', 'taebaeksan', 8, '산림청 100대 명산', null),
  ('forest_service_100', 'odaesan', 9, '산림청 100대 명산', null),
  ('forest_service_100', 'gariwangsan', 10, '산림청 100대 명산', null),
  ('forest_service_100', 'hwaaksan', 11, '산림청 100대 명산', null),
  ('forest_service_100', 'bangtaesan', 12, '산림청 100대 명산', null),
  ('forest_service_100', 'gayasan', 13, '산림청 100대 명산', null),
  ('forest_service_100', 'jeombongsan', 14, '산림청 100대 명산', null),
  ('forest_service_100', 'dutasan', 15, '산림청 100대 명산', null),
  ('forest_service_100', 'baekdeoksan', 16, '산림청 100대 명산', null),
  ('forest_service_100', 'daeamsan', 17, '산림청 100대 명산', null),
  ('forest_service_100', 'chiaksan', 18, '산림청 100대 명산', null),
  ('forest_service_100', 'myeongjisan', 19, '산림청 100대 명산', null),
  ('forest_service_100', 'minjujisan', 20, '산림청 100대 명산', null),
  ('forest_service_100', 'gajisan', 21, '산림청 100대 명산', null),
  ('forest_service_100', 'jangansan', 22, '산림청 100대 명산', null),
  ('forest_service_100', 'baegunsan-gwangyang', 23, '산림청 100대 명산', null),
  ('forest_service_100', 'unmunsan', 24, '산림청 100대 명산', null),
  ('forest_service_100', 'palgongsan', 25, '산림청 100대 명산', null),
  ('forest_service_100', 'hwangseoksan', 26, '산림청 100대 명산', null),
  ('forest_service_100', 'mudeungsan', 27, '산림청 100대 명산', null),
  ('forest_service_100', 'sinbulsan', 28, '산림청 100대 명산', null),
  ('forest_service_100', 'yongmunsan', 29, '산림청 100대 명산', null),
  ('forest_service_100', 'unjangsan', 30, '산림청 100대 명산', null),
  ('forest_service_100', 'hwangaksan', 31, '산림청 100대 명산', null),
  ('forest_service_100', 'jaeyaksan', 32, '산림청 100대 명산', null),
  ('forest_service_100', 'hwangmaesan', 33, '산림청 100대 명산', null),
  ('forest_service_100', 'juheulsan', 34, '산림청 100대 명산', null),
  ('forest_service_100', 'woraksan', 35, '산림청 100대 명산', null),
  ('forest_service_100', 'biseulsan', 36, '산림청 100대 명산', null),
  ('forest_service_100', 'hwangjangsan', 37, '산림청 100대 명산', null),
  ('forest_service_100', 'deokhangsan', 38, '산림청 100대 명산', null),
  ('forest_service_100', 'songnisan', 39, '산림청 100대 명산', null),
  ('forest_service_100', 'garisan', 40, '산림청 100대 명산', null),
  ('forest_service_100', 'jeoksangsan', 41, '산림청 100대 명산', null),
  ('forest_service_100', 'taehwasan', 42, '산림청 100대 명산', null),
  ('forest_service_100', 'geumsusan', 43, '산림청 100대 명산', null),
  ('forest_service_100', 'eungbongsan', 44, '산림청 100대 명산', null),
  ('forest_service_100', 'huiyangsan', 45, '산림청 100대 명산', null),
  ('forest_service_100', 'seonginbong', 46, '산림청 100대 명산', null),
  ('forest_service_100', 'geumosan', 47, '산림청 100대 명산', null),
  ('forest_service_100', 'doraksan', 48, '산림청 100대 명산', null),
  ('forest_service_100', 'unaksan', 49, '산림청 100대 명산', null),
  ('forest_service_100', 'daeyasan', 50, '산림청 100대 명산', null),
  ('forest_service_100', 'myeongseongsan', 51, '산림청 100대 명산', null),
  ('forest_service_100', 'cheonseongsan', 52, '산림청 100대 명산', null),
  ('forest_service_100', 'baegunsan-pocheon', 53, '산림청 100대 명산', null),
  ('forest_service_100', 'seodaesan', 54, '산림청 100대 명산', null),
  ('forest_service_100', 'gongjaksan', 55, '산림청 100대 명산', null),
  ('forest_service_100', 'chungnyeongsan', 56, '산림청 100대 명산', null),
  ('forest_service_100', 'jogyesan', 57, '산림청 100대 명산', null),
  ('forest_service_100', 'baegunsan-jeongseon', 58, '산림청 100대 명산', null),
  ('forest_service_100', 'daedunsan', 59, '산림청 100대 명산', null),
  ('forest_service_100', 'yonghwasan', 60, '산림청 100대 명산', null),
  ('forest_service_100', 'gubyeongsan', 61, '산림청 100대 명산', null),
  ('forest_service_100', 'cheongnyangsan', 62, '산림청 100대 명산', null),
  ('forest_service_100', 'yumyeongsan', 63, '산림청 100대 명산', null),
  ('forest_service_100', 'gyeryongsan', 64, '산림청 100대 명산', null),
  ('forest_service_100', 'cheonmasan', 65, '산림청 100대 명산', null),
  ('forest_service_100', 'wolchulsan', 66, '산림청 100대 명산', null),
  ('forest_service_100', 'geumjeongsan', 67, '산림청 100대 명산', null),
  ('forest_service_100', 'moaksan', 68, '산림청 100대 명산', null),
  ('forest_service_100', 'gitdaebong-hongdo', 69, '산림청 100대 명산', null),
  ('forest_service_100', 'obongsan', 70, '산림청 100대 명산', null),
  ('forest_service_100', 'naejangsan', 71, '산림청 100대 명산', null),
  ('forest_service_100', 'muhaksan', 72, '산림청 100대 명산', null),
  ('forest_service_100', 'hwawangsan', 73, '산림청 100대 명산', null),
  ('forest_service_100', 'bangjangsan', 74, '산림청 100대 명산', null),
  ('forest_service_100', 'baegamsan', 75, '산림청 100대 명산', null),
  ('forest_service_100', 'dobongsan', 76, '산림청 100대 명산', null),
  ('forest_service_100', 'chuwolsan', 77, '산림청 100대 명산', null),
  ('forest_service_100', 'cheongwansan', 78, '산림청 100대 명산', null),
  ('forest_service_100', 'juwangsan', 79, '산림청 100대 명산', null),
  ('forest_service_100', 'cheontaesan', 80, '산림청 100대 명산', null),
  ('forest_service_100', 'naeyeonsan', 81, '산림청 100대 명산', null),
  ('forest_service_100', 'duryunsan', 82, '산림청 100대 명산', null),
  ('forest_service_100', 'maisan', 83, '산림청 100대 명산', null),
  ('forest_service_100', 'geumsan', 84, '산림청 100대 명산', null),
  ('forest_service_100', 'gamaksan', 85, '산림청 100대 명산', null),
  ('forest_service_100', 'samaksan', 86, '산림청 100대 명산', null),
  ('forest_service_100', 'gwanaksan', 87, '산림청 100대 명산', null),
  ('forest_service_100', 'paryeongsan', 88, '산림청 100대 명산', null),
  ('forest_service_100', 'soyosan', 89, '산림청 100대 명산', null),
  ('forest_service_100', 'gangcheonsan', 90, '산림청 100대 명산', null),
  ('forest_service_100', 'chilgapsan', 91, '산림청 100대 명산', null),
  ('forest_service_100', 'yeonhwasan', 92, '산림청 100대 명산', null),
  ('forest_service_100', 'byeonsan', 93, '산림청 100대 명산', null),
  ('forest_service_100', 'deoksungsan', 94, '산림청 100대 명산', null),
  ('forest_service_100', 'manisan', 95, '산림청 100대 명산', null),
  ('forest_service_100', 'namsan-gyeongju', 96, '산림청 100대 명산', null),
  ('forest_service_100', 'mireuksan', 97, '산림청 100대 명산', null),
  ('forest_service_100', 'jirisan-tongyeong', 98, '산림청 100대 명산', null),
  ('forest_service_100', 'seonunsan', 99, '산림청 100대 명산', null),
  ('forest_service_100', 'palbongsan', 100, '산림청 100대 명산', null),
  ('bac_100', 'gwanaksan', 1, '관악산', '정상'),
  ('bac_100', 'dobongsan', 2, '도봉산', '신선대'),
  ('bac_100', 'bukhansan', 3, '북한산', '백운대'),
  ('bac_100', 'suraksan', 4, '수락산', '주봉'),
  ('bac_100', 'cheonggyesan-seoul', 5, '청계산', '매봉'),
  ('bac_100', 'geumjeongsan', 6, '금정산', '고당봉'),
  ('bac_100', 'biseulsan', 7, '비슬산', '천왕봉'),
  ('bac_100', 'manisan', 8, '마니산(강화도)', '정상'),
  ('bac_100', 'mudeungsan', 9, '무등산', '서석대 정상석/인왕봉 정상석'),
  ('bac_100', 'gyeryongsan', 10, '계룡산', '관음봉'),
  ('bac_100', 'sinbulsan', 11, '신불산', '정상'),
  ('bac_100', 'gajisan', 12, '가지산', '정상'),
  ('bac_100', 'yeoninsan', 13, '연인산', '정상'),
  ('bac_100', 'myeongjisan', 14, '명지산', '정상'),
  ('bac_100', 'hwaaksan', 15, '화악산(가평)', '중봉'),
  ('bac_100', 'yumyeongsan', 16, '유명산', '정상'),
  ('bac_100', 'gamaksan', 17, '감악산(파주)', '정상'),
  ('bac_100', 'cheonmasan', 18, '천마산', '정상석'),
  ('bac_100', 'soyosan', 19, '소요산', '의상대'),
  ('bac_100', 'yongmunsan', 20, '용문산(양평)', '가섭봉 정상석'),
  ('bac_100', 'gamaksan-wonju', 21, '감악산(원주)', '원주/제천 정상석'),
  ('bac_100', 'garisan', 22, '가리산(홍천)', '정상'),
  ('bac_100', 'gariwangsan', 23, '가리왕산', '정상'),
  ('bac_100', 'gyebangsan', 24, '계방산', '정상'),
  ('bac_100', 'deokhangsan', 25, '덕항산', '정상'),
  ('bac_100', 'dutasan', 26, '두타산', '정상'),
  ('bac_100', 'bangtaesan', 27, '방태산', '주억봉'),
  ('bac_100', 'baekdeoksan', 28, '백덕산', '정상'),
  ('bac_100', 'baegunsan-jeongseon', 29, '백운산(동강)', '정상'),
  ('bac_100', 'samaksan', 30, '삼악산', '용화봉'),
  ('bac_100', 'seoraksan', 31, '설악산', '대청봉'),
  ('bac_100', 'odaesan-noinbong', 32, '오대산 노인봉', '노인봉'),
  ('bac_100', 'odaesan', 33, '오대산 비로봉', '비로봉'),
  ('bac_100', 'obongsan', 34, '오봉산(춘천)', '정상(5봉)'),
  ('bac_100', 'yonghwasan', 35, '용화산', '정상'),
  ('bac_100', 'eungbongsan', 36, '응봉산(울진)', '정상'),
  ('bac_100', 'chiaksan', 37, '치악산', '비로봉'),
  ('bac_100', 'taebaeksan', 38, '태백산', '천제단'),
  ('bac_100', 'taehwasan', 39, '태화산', '정상'),
  ('bac_100', 'palbongsan', 40, '팔봉산(홍천)', '팔봉산(2봉인증)'),
  ('bac_100', 'hambaeksan', 41, '함백산', '정상'),
  ('bac_100', 'gubyeongsan', 42, '구병산(보은)', '정상'),
  ('bac_100', 'geumsusan', 43, '금수산', '정상'),
  ('bac_100', 'daeyasan', 44, '대야산', '정상'),
  ('bac_100', 'doraksan', 45, '도락산', '정상'),
  ('bac_100', 'minjujisan', 46, '민주지산', '정상'),
  ('bac_100', 'songnisan', 47, '속리산', '천왕봉'),
  ('bac_100', 'woraksan', 48, '월악산', '영봉'),
  ('bac_100', 'cheontaesan', 49, '천태산', '정상'),
  ('bac_100', 'cheonghwasan', 50, '청화산', '정상'),
  ('bac_100', 'chilbosan-goesan', 51, '칠보산(괴산)', '정상'),
  ('bac_100', 'gayasan-yesan', 52, '가야산(충남)', '정상(정상석 설치)'),
  ('bac_100', 'gwangdeoksan-cheonan', 53, '광덕산', '정상'),
  ('bac_100', 'daedunsan', 54, '대둔산', '마천대'),
  ('bac_100', 'oseosan', 55, '오서산(보령)', '정상'),
  ('bac_100', 'yongbongsan-hongseong', 56, '용봉산(홍성)', '정상'),
  ('bac_100', 'chilgapsan', 57, '칠갑산(청양)', '정상'),
  ('bac_100', 'gubongsan-jinan', 58, '구봉산(진안)', '천왕봉'),
  ('bac_100', 'byeonsan', 59, '내변산(부안)', '관음봉'),
  ('bac_100', 'naejangsan', 60, '내장산', '신선봉'),
  ('bac_100', 'deogyusan', 61, '덕유산', '향적봉'),
  ('bac_100', 'maisan', 62, '마이산(진안)', '비룡대'),
  ('bac_100', 'moaksan', 63, '모악산', '정상'),
  ('bac_100', 'seonunsan', 64, '선운산', '수리봉'),
  ('bac_100', 'unjangsan', 65, '운장산', '운장대'),
  ('bac_100', 'jangansan', 66, '장안산', '정상'),
  ('bac_100', 'jirisan-baraebong', 67, '지리산 바래봉', '바래봉'),
  ('bac_100', 'jirisan-banyabong', 68, '지리산 반야봉', '반야봉'),
  ('bac_100', 'dalmasan', 69, '달마산', '달마봉'),
  ('bac_100', 'deongnyongsan', 70, '덕룡산', '서봉'),
  ('bac_100', 'dongaksan-gokseong', 71, '동악산(곡성)', '시루봉'),
  ('bac_100', 'duryunsan', 72, '두륜산', '가련봉'),
  ('bac_100', 'bangjangsan', 73, '방장산', '정상'),
  ('bac_100', 'baegamsan', 74, '백암산', '상왕봉'),
  ('bac_100', 'baegunsan-gwangyang', 75, '백운산(광양)', '상봉'),
  ('bac_100', 'bulgapsan-yeonggwang', 76, '불갑산(영광)', '연실봉'),
  ('bac_100', 'wolchulsan', 77, '월출산', '천황봉 정상석'),
  ('bac_100', 'jogyesan', 78, '조계산', '장군봉'),
  ('bac_100', 'cheongwansan', 79, '천관산', '연대봉'),
  ('bac_100', 'chungnyeongsan-jangseong', 80, '축령산(장성)', '정상'),
  ('bac_100', 'paryeongsan', 81, '팔영산', '깃대봉'),
  ('bac_100', 'geumosan', 82, '금오산(구미)', '현월봉'),
  ('bac_100', 'namsan-gyeongju', 83, '남산(경주)', '금오봉'),
  ('bac_100', 'naeyeonsan', 84, '내연산', '삼지봉'),
  ('bac_100', 'sobaeksan', 85, '소백산', '비로봉'),
  ('bac_100', 'joryeongsan', 86, '조령산', '정상'),
  ('bac_100', 'juwangsan', 87, '주왕산', '주봉'),
  ('bac_100', 'juheulsan', 88, '주흘산', '주봉'),
  ('bac_100', 'cheongnyangsan', 89, '청량산', '장인봉'),
  ('bac_100', 'palgongsan', 90, '팔공산', '비로봉'),
  ('bac_100', 'hwangaksan', 91, '황악산(김천)', '정상'),
  ('bac_100', 'gayasan', 92, '가야산(경상)', '정상'),
  ('bac_100', 'jaeyaksan', 93, '재약산', '수미봉'),
  ('bac_100', 'jirisan', 94, '지리산', '지리산 천왕봉'),
  ('bac_100', 'cheonseongsan', 95, '천성산', '원효봉'),
  ('bac_100', 'hwawangsan', 96, '화왕산(창녕)', '정상'),
  ('bac_100', 'hwangmaesan', 97, '황매산(산청)', '정상'),
  ('bac_100', 'hwangseoksan', 98, '황석산(함양)', '황석산 정상석'),
  ('bac_100', 'unaksan', 99, '운악산', '서봉'),
  ('bac_100', 'hallasan', 100, '한라산', '백록담');

-- BAC checkpoint names are safe to seed, but coordinates and radii are not.
-- Existing verified points are preserved when this seed is rerun.
insert into public.verification_points (
  mountain_id,
  name_ko,
  latitude,
  longitude,
  verification_radius_m,
  coordinate_status,
  source_note
)
select
  mountain.id,
  seed.verification_point_name,
  null,
  null,
  null,
  'pending',
  'BAC 명산100 공개 목록의 인증지명(2026-09-08 확인). GPS 좌표와 인증 반경은 미검증.'
from collection_membership_seed seed
join public.mountains mountain on mountain.slug = seed.mountain_slug
where seed.collection_id = 'bac_100'
  and seed.verification_point_name is not null
on conflict (mountain_id, name_ko) do nothing;

delete from public.collection_mountains
where collection_id in ('forest_service_100', 'bac_100');

insert into public.collection_mountains (
  collection_id,
  mountain_id,
  verification_point_id,
  display_order,
  source_label
)
select
  seed.collection_id,
  mountain.id,
  point.id,
  seed.display_order,
  seed.source_label
from collection_membership_seed seed
join public.mountains mountain on mountain.slug = seed.mountain_slug
left join public.verification_points point
  on point.mountain_id = mountain.id
 and point.name_ko = seed.verification_point_name
on conflict (collection_id, mountain_id) do update set
  verification_point_id = excluded.verification_point_id,
  display_order = excluded.display_order,
  source_label = excluded.source_label;

do $$
declare
  forest_count integer;
  bac_count integer;
  shared_count integer;
  bac_linked_point_count integer;
  unsafe_pending_point_count integer;
  desired_identity_count integer;
  available_identity_count integer;
begin
  select count(distinct mountain_slug) into desired_identity_count
  from collection_membership_seed;

  select count(distinct seed.mountain_slug) into available_identity_count
  from collection_membership_seed seed
  join public.mountains mountain on mountain.slug = seed.mountain_slug;

  select count(*) into forest_count
  from public.collection_mountains
  where collection_id = 'forest_service_100';

  select count(*) into bac_count
  from public.collection_mountains
  where collection_id = 'bac_100';

  select count(*) into shared_count
  from public.collection_mountains forest
  join public.collection_mountains bac on bac.mountain_id = forest.mountain_id
  where forest.collection_id = 'forest_service_100'
    and bac.collection_id = 'bac_100';

  select count(*) into bac_linked_point_count
  from public.collection_mountains
  where collection_id = 'bac_100'
    and verification_point_id is not null;

  select count(*) into unsafe_pending_point_count
  from public.collection_mountains membership
  join public.verification_points point on point.id = membership.verification_point_id
  where membership.collection_id = 'bac_100'
    and point.coordinate_status = 'pending'
    and (
      point.latitude is not null
      or point.longitude is not null
      or point.verification_radius_m is not null
    );

  if available_identity_count = desired_identity_count
     and (
       forest_count <> 100
       or bac_count <> 100
       or shared_count <> 79
       or bac_linked_point_count <> 100
       or unsafe_pending_point_count <> 0
     )
  then
    raise exception
      'invalid collection seed: forest=%, bac=%, shared=%, bac_points=%, unsafe_pending=%',
      forest_count,
      bac_count,
      shared_count,
      bac_linked_point_count,
      unsafe_pending_point_count;
  end if;
end;
$$;
