#!/usr/bin/env node
/**
 * Generates supabase/seed.sql from src/data/mountains.json.
 * Run: node scripts/generate-seed.js
 */
const fs = require('node:fs');
const path = require('node:path');

const mountains = require('../src/data/mountains.json');

const q = (value) => (value === null || value === undefined ? 'null' : `'${String(value).replace(/'/g, "''")}'`);

const rows = mountains.map(
  (m) =>
    `  (${q(m.slug)}, ${q(m.name_ko)}, ${q(m.name_en)}, ${m.altitude_m}, ${q(m.region)}, ${m.latitude}, ${m.longitude}, ${m.verification_radius_m}, ${q(m.image_url)}, ${q(m.mascot_key)}, ${q(m.description)}, ${m.display_order})`,
);

const sql = `-- Generated by scripts/generate-seed.js from src/data/mountains.json. Do not edit by hand.
-- 100 famous mountains of Korea (산림청 100대 명산). Coordinates are approximate
-- summit positions and must be verified before GPS certification goes live.

insert into public.mountains
  (slug, name_ko, name_en, altitude_m, region, latitude, longitude, verification_radius_m, image_url, mascot_key, description, display_order)
values
${rows.join(',\n')}
on conflict (slug) do update set
  name_ko = excluded.name_ko,
  name_en = excluded.name_en,
  altitude_m = excluded.altitude_m,
  region = excluded.region,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  verification_radius_m = excluded.verification_radius_m,
  image_url = coalesce(public.mountains.image_url, excluded.image_url),
  mascot_key = excluded.mascot_key,
  description = excluded.description,
  display_order = excluded.display_order;
`;

const out = path.join(__dirname, '..', 'supabase', 'seed.sql');
fs.writeFileSync(out, sql);
console.log(`wrote ${out} (${mountains.length} mountains)`);
