// Generated by scripts/sync-open-license-mountain-images.mjs. Do not edit by hand.
export const OPEN_LICENSE_MOUNTAIN_IMAGES = {
  "gamaksan-wonju": {
    source: require("../../assets/photos/open-license-mountains/gamaksan-wonju.jpg"),
    author: "한국학중앙연구원 「감악산」 (제작: 충청북도문화재연구원)",
    license: "공공누리 제1유형",
    licenseUrl: "https://www.kogl.or.kr/info/licenseType1.do",
    sourceUrl: "https://jecheon.grandculture.net/Image?localName=jecheon&id=GC033P00886",
    articleUrl: "https://jecheon.grandculture.net/jecheon/search/GC033P00886",
  },
  "gubongsan-jinan": {
    source: require("../../assets/photos/open-license-mountains/gubongsan-jinan.jpg"),
    author: "박정병 「진안_구봉산_00054」",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/deed.ko",
    sourceUrl: "https://gongu.copyright.or.kr/gongu/wrt/cmmn/wrtFileDownload.do?wrtSn=11052345&fileSn=1",
    articleUrl: "https://gongu.copyright.or.kr/gongu/wrt/wrt/view.do?menuNo=200018&wrtSn=11052345",
  },
  "dongaksan-gokseong": {
    source: require("../../assets/photos/open-license-mountains/dongaksan-gokseong.jpg"),
    author: "곡성군·나종화 「봄여행- 동악산에 그려진 한반도 지도를 찾아서」",
    license: "공공누리 제2유형",
    licenseUrl: "https://www.kogl.or.kr/info/licenseType2.do",
    sourceUrl: "https://www.gokseong.go.kr/tour/ybscript.io/common/file_download/97920/11591/_P6A8569.jpg",
    articleUrl: "https://www.gokseong.go.kr/tour/tourguide/recommended_site?idx=97920&mode=view",
  },
} as const;
